spring :
 application :
  name : config-server-service

 cloud :
  config :
   server :
    git :
     uri : https://github.com/hims-git/environment-variable-repo.git
     default-label : master


server :
  port : ${port:8888}
